<MatchaComponentsScreen>
    name: "matcha components screen"
    BoxLayout:
        orientation: "vertical"
        CustomLabel:
            text: "hello"
            color: app.theme_cls.primary_color
            adaptive_height: True
            bg_color: "red"
        IconButton:
            icon: "android"
            color: app.theme_cls.primary_color
            bg_color: app.theme_cls.primary_color[:3] + [.2]
            line_color: app.theme_cls.primary_color[:3] + [.3]
